# Generated by Django 2.1.7 on 2019-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('ms', models.CharField(max_length=200)),
                ('type', models.IntegerField(max_length=10)),
                ('stop', models.IntegerField(max_length=23)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
